// Declarations for static asset imports used across the app
declare module "*.css";
declare module "*.module.css";
declare module "*.scss";
declare module "*.module.scss";
declare module "*.png";
declare module "*.jpg";
declare module "*.jpeg";
declare module "*.svg" {
  const content: string;
  export default content;
}

// Allow importing JSON-like route types generated by Next
declare module "*.json" {
  const value: any;
  export default value;
}
